### ISSUE TITLE
Reflect change to mina-governance

### ISSUE THREAD

**Issue by Isaac-DeFrain** [Granola-Team/mina-governance#159]
We should change the documentation from on-chain signaling to mina-governance!

**Comment by trevorbernard** [comment]
Anything public facing likely has to be approved by Mina. Adding to the next meetings agenda.

**Comment by Isaac-DeFrain** [comment]
Agreed. This change was requested by David Sedgewick at Mina

**Comment by trevorbernard** [comment]
Spoke about this with Ben and John. Won't do
